config/routes.rb
Dtebridge::Application.routes.draw do

  
  resources :usuarioempresas

  resources :envioclientes


  resources :compmanuals do
    collection { post :import }
  end

  resources :docmanuals do
    collection { post :import }
  end

  resources :log_iats
  resources :otrosimpmanuals
  resources :otrosimpcompmanuals
  resources :tipodtes
  resources :sucursals
  resources :empresas
  resources :subdsctos
  resources :cdgitems
  resources :comisioncompras
  resources :refdetcompras
  resources :dscrcgglobalcompras
  resources :imptoretencompras
  resources :mpagocompras
  resources :docsemails
  resources :doccompras
  resources :comisions
  resources :ref_detalles
  resources :dsc_rcg_globals
  resources :impuesto_retens
  resources :monto_pagos
  resources :detalles
  resources :documentos
  resources :iat_logs
  resources :iats
  resources :libros
  
  devise_for :installs
  devise_for :users

  get "report/venta"
  post "report/find", to: "report#find"
  get "report/compra"
  post "report/findCompra", to: "report#findCompra"

  get "detlibrovta/index"
  get "uploadformat/index"
  get "newuser/index"
  get "detlibro/index"


  get "libro_compra/index"
  post "buscarLibroCompra", to: "libro_compra#find"
  get "libro_compra/generalibro", to: "libro_compra#generalibro"

  get "listalibro/index"
  get "home/index"
  get "libro_venta/index"
  post "buscarLibrovta", to: "libro_venta#find"
  get "libro_venta/generalibro", to: "libro_venta#generalibro"

  get "listalibro/sendsii/:id", to: "listalibro#sendsii"

 
  get "doccompras_aprob/index"
  get "doccompras_rech/index"
  get "get_siitoken", to: "connectsii#get_token"
  get "postsii" , to: "connectsii#postsii"
  get "setDTE" , to: "connectsii#createenvio"
  get "respIntercam" , to: "connectsii#resp_intercambio"
  get "recepMercaderia" , to: "connectsii#recep_mercaderia"
  get "aprobComercial" , to: "connectsii#aprob_comercial"
  get "estadistica/index"
  get "estadistica", to: "estadistica#index"
  get "/contribuyentes/upload", to: "contribuyentes#upload"
 
  get "listalibro/genxml/:id", to: "listalibro#genxml"
  get "listalibro/sendxml/:id", to: "listalibro#sendxml"
  get "detlibro/index/:id", to: "detlibro#index"

  get "detcompras/:id", to: "detcompras#index"
  
  get "doccompras/rechazar/:id", to: "doccompras#rechazar"
  get "doccompras/aprobar/:id", to: "doccompras#aprobar"
  get "doccompras/sendxml/:id", to: "doccompras#sendxml"
  get "doccompras_aprob/rechazar/:id", to: "doccompras_aprob#rechazar"
  get "doccompras_rech/aprobar/:id", to: "doccompras_rech#aprobar"
  get "doccompras_aprob", to: "doccompras_aprob#index"
  get "doccompras_rech", to: "doccompras_rech#index"

  post "buscarDoc", to: "documentos#find"

  get "documentos/download", to: "documentos#download"

  get "/daradmin/permisos", to: "daradmin#index"
  get "/daradmin/:id", to: "daradmin#daradmin"
  get "/daradmin/quitaradmin/:id", to: "daradmin#quitaradmin"

  get "/newuser/index", to: "newuser#index"
  post "/newuser/new", to: "newuser#new"

  get "/uploadformat/fileventas", to: "uploadformat#sendfileventas"
  get "/uploadformat/filecompras", to: "uploadformat#sendfilecompras"

  root to: "home#index"

  resources :contribuyentes do
    collection { post :import }
  end

  namespace :api do
    namespace :v1 do
      post "/pruebas", to: "pruebas#create"
      post "/iat_doc", to: "iat#iat_doc"
      post "/invoice", to: "documento#create_doc"
      get  "/pruebas", to: "pruebas#index"
      get "/iat_login", to: "iat#login"
      get "/iat_ping/:id", to: "iat#ping"
      get "/iat_offline", to: "iat#isoffline"
      get "/gettoken", to: "documento#get_token"
      get "/procestado", to: "documento#procesoEstado"
      get "/notification", to: "notification#send_notif"
      get "/procesarecibo", to: "doccompra#procesarecibo"
      get "/resend", to: "documento#resend"
      get "/sendclient", to: "documento#sendclient"
      get "/separchivo", to: "separchivo#separchivo"
      get "/readmail", to: "readmail#readmail"
     end
  end

end

app/models/otrosimpmanual.rb
class Otrosimpmanual < ActiveRecord::Base
  belongs_to :docmanual
end

app/controllers/otrosimpmanuals_controller.rb
class OtrosimpmanualsController < ApplicationController
  before_action :set_otrosimpmanual, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @otrosimpmanuals = Otrosimpmanual.all
    respond_with(@otrosimpmanuals)
  end

  def show
    respond_with(@otrosimpmanual)
  end

  def new
    @otrosimpmanual = Otrosimpmanual.new
    respond_with(@otrosimpmanual)
  end

  def edit
  end

  def create
    @otrosimpmanual = Otrosimpmanual.new(otrosimpmanual_params)
    @otrosimpmanual.save
    respond_with(@otrosimpmanual)
  end

  def update
    @otrosimpmanual.update(otrosimpmanual_params)
    respond_with(@otrosimpmanual)
  end

  def destroy
    @otrosimpmanual.destroy
    respond_with(@otrosimpmanual)
  end

  private
    def set_otrosimpmanual
      @otrosimpmanual = Otrosimpmanual.find(params[:id])
    end

    def otrosimpmanual_params
      params.require(:otrosimpmanual).permit(:TipoImp, :TasaImp, :MontoImp, :docmanual_id)
    end
end

app/views/otrosimpmanuals/_form.html.haml
= simple_form_for(@otrosimpmanual) do |f|
  = f.error_notification

  .form-inputs
    = f.input :TipoImp
    = f.input :TasaImp
    = f.input :MontoImp
    = f.association :docmanual

  .form-actions
    = f.button :submit

app/views/otrosimpmanuals/edit.html.haml
%h1 Editing otrosimpmanual

= render 'form'

= link_to 'Show', @otrosimpmanual
\|
= link_to 'Back', otrosimpmanuals_path

app/views/otrosimpmanuals/index.html.haml
%h1 Listing otrosimpmanuals

%table
  %thead
    %tr
      %th Tipoimp
      %th Tasaimp
      %th Montoimp
      %th Docmanual
      %th
      %th
      %th
      
  %tbody
    - @otrosimpmanuals.each do |otrosimpmanual|
      %tr
        %td= otrosimpmanual.TipoImp
        %td= otrosimpmanual.TasaImp
        %td= otrosimpmanual.MontoImp
        %td= otrosimpmanual.docmanual
        %td= link_to 'Show', otrosimpmanual
        %td= link_to 'Edit', edit_otrosimpmanual_path(otrosimpmanual)
        %td= link_to 'Destroy', otrosimpmanual, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Otrosimpmanual', new_otrosimpmanual_path

app/views/otrosimpmanuals/new.html.haml
%h1 New otrosimpmanual

= render 'form'

= link_to 'Back', otrosimpmanuals_path

app/views/otrosimpmanuals/show.html.haml
%p#notice= notice

%p
  %b Tipoimp:
  = @otrosimpmanual.TipoImp
%p
  %b Tasaimp:
  = @otrosimpmanual.TasaImp
%p
  %b Montoimp:
  = @otrosimpmanual.MontoImp
%p
  %b Docmanual:
  = @otrosimpmanual.docmanual

= link_to 'Edit', edit_otrosimpmanual_path(@otrosimpmanual)
\|
= link_to 'Back', otrosimpmanuals_path