config/routes.rb
Dtebridge::Application.routes.draw do

  
  resources :usuarioempresas

  resources :envioclientes


  resources :compmanuals do
    collection { post :import }
  end

  resources :docmanuals do
    collection { post :import }
  end

  resources :log_iats
  resources :otrosimpmanuals
  resources :otrosimpcompmanuals
  resources :tipodtes
  resources :sucursals
  resources :empresas
  resources :subdsctos
  resources :cdgitems
  resources :comisioncompras
  resources :refdetcompras
  resources :dscrcgglobalcompras
  resources :imptoretencompras
  resources :mpagocompras
  resources :docsemails
  resources :doccompras
  resources :comisions
  resources :ref_detalles
  resources :dsc_rcg_globals
  resources :impuesto_retens
  resources :monto_pagos
  resources :detalles
  resources :documentos
  resources :iat_logs
  resources :iats
  resources :libros
  
  devise_for :installs
  devise_for :users

  get "report/venta"
  post "report/find", to: "report#find"
  get "report/compra"
  post "report/findCompra", to: "report#findCompra"

  get "detlibrovta/index"
  get "uploadformat/index"
  get "newuser/index"
  get "detlibro/index"


  get "libro_compra/index"
  post "buscarLibroCompra", to: "libro_compra#find"
  get "libro_compra/generalibro", to: "libro_compra#generalibro"

  get "listalibro/index"
  get "home/index"
  get "libro_venta/index"
  post "buscarLibrovta", to: "libro_venta#find"
  get "libro_venta/generalibro", to: "libro_venta#generalibro"

  get "listalibro/sendsii/:id", to: "listalibro#sendsii"

 
  get "doccompras_aprob/index"
  get "doccompras_rech/index"
  get "get_siitoken", to: "connectsii#get_token"
  get "postsii" , to: "connectsii#postsii"
  get "setDTE" , to: "connectsii#createenvio"
  get "respIntercam" , to: "connectsii#resp_intercambio"
  get "recepMercaderia" , to: "connectsii#recep_mercaderia"
  get "aprobComercial" , to: "connectsii#aprob_comercial"
  get "estadistica/index"
  get "estadistica", to: "estadistica#index"
  get "/contribuyentes/upload", to: "contribuyentes#upload"
 
  get "listalibro/genxml/:id", to: "listalibro#genxml"
  get "listalibro/sendxml/:id", to: "listalibro#sendxml"
  get "detlibro/index/:id", to: "detlibro#index"

  get "detcompras/:id", to: "detcompras#index"
  
  get "doccompras/rechazar/:id", to: "doccompras#rechazar"
  get "doccompras/aprobar/:id", to: "doccompras#aprobar"
  get "doccompras/sendxml/:id", to: "doccompras#sendxml"
  get "doccompras_aprob/rechazar/:id", to: "doccompras_aprob#rechazar"
  get "doccompras_rech/aprobar/:id", to: "doccompras_rech#aprobar"
  get "doccompras_aprob", to: "doccompras_aprob#index"
  get "doccompras_rech", to: "doccompras_rech#index"

  post "buscarDoc", to: "documentos#find"

  get "documentos/download", to: "documentos#download"

  get "/daradmin/permisos", to: "daradmin#index"
  get "/daradmin/:id", to: "daradmin#daradmin"
  get "/daradmin/quitaradmin/:id", to: "daradmin#quitaradmin"

  get "/newuser/index", to: "newuser#index"
  post "/newuser/new", to: "newuser#new"

  get "/uploadformat/fileventas", to: "uploadformat#sendfileventas"
  get "/uploadformat/filecompras", to: "uploadformat#sendfilecompras"

  root to: "home#index"

  resources :contribuyentes do
    collection { post :import }
  end

  namespace :api do
    namespace :v1 do
      post "/pruebas", to: "pruebas#create"
      post "/iat_doc", to: "iat#iat_doc"
      post "/invoice", to: "documento#create_doc"
      get  "/pruebas", to: "pruebas#index"
      get "/iat_login", to: "iat#login"
      get "/iat_ping/:id", to: "iat#ping"
      get "/iat_offline", to: "iat#isoffline"
      get "/gettoken", to: "documento#get_token"
      get "/procestado", to: "documento#procesoEstado"
      get "/notification", to: "notification#send_notif"
      get "/procesarecibo", to: "doccompra#procesarecibo"
      get "/resend", to: "documento#resend"
      get "/sendclient", to: "documento#sendclient"
      get "/separchivo", to: "separchivo#separchivo"
      get "/readmail", to: "readmail#readmail"
     end
  end

end

app/models/docmanual.rb
# encoding: UTF-8
class Docmanual < ActiveRecord::Base
  require 'csv'

  has_many :otrosimpmanuals, dependent: :destroy

  attr_reader :nombre_doc
  def nombre_doc
    tipo = Tipodte.where(tipo: self.tipodoc).first 
    return (tipo.nil? ? self.tipodoc : tipo.nombre)
  end

  def self.import(file)
    fileOk = false
    msg=" "
    begin
      CSV.foreach(file.path, col_sep: ';', headers: true, encoding: "ISO-8859-1" ) do |row|
        rowHash = row.to_hash
       
        if rowHash["fchemis"][0..3].index("-") != nil || rowHash["fchemis"].index("/") != nil
          msg = msg + "Documento folio " + rowHash["folio"] +", formato fecha incorrecto, debe ser : aaaa-mm-dd \r\n"
        end  

        montotot = rowHash["mntneto"].to_f + rowHash["mntexe"].to_f + rowHash["mntiva"].to_f + rowHash["otrosimpto"].to_f + rowHash["impto18"].to_f + rowHash["impto10"].to_f + rowHash["impto25"].to_f + rowHash["impto30"].to_f
        if montotot != rowHash["mnttotal"].to_f 
          msg =  msg + "Documento folio " + rowHash["folio"] + " montos no cuadran.  \r\n" 
        end

        if (rowHash["mntneto"].to_f*0.19).round(0) != rowHash["mntiva"].to_f.round(0)
          msg =  msg + "Documento folio " + rowHash["folio"] + ", monto Iva no cuadra.  \r\n"
        end

        if msg != " "
          return msg
        else
          fileOk = true
        end    
      end
    rescue
      msg = msg + "Formato de archivo incorrecto, revise si contiene algún caracter especial \r\n"
      puts "****************"
      puts msg
      puts puts "Error #{$!}"
      puts "****************"  
      return msg    
    end  

    if fileOk
      CSV.foreach(file.path, col_sep: ';', headers: true) do |row|
        rowHash = row.to_hash
        rowHash["rznsocrecep"] = rowHash["rznsocrecep"][0..49].gsub('&','')
        rowHash["rutemisor"] = rowHash["rutemisor"].gsub('.','')
        rowHash["rutemisor"] = rowHash["rutemisor"].gsub('k','K')
        rowHash["rutrecep"] = rowHash["rutrecep"].gsub('.','')
        rowHash["rutrecep"] = rowHash["rutrecep"].gsub('k','K')

        if rowHash["impto10"]==nil
          rowHash["impto10"]="0"
        end  
        if rowHash["impto18"]==nil
          rowHash["impto18"]="0"
        end  
        if rowHash["impto25"]==nil
          rowHash["impto25"]="0"
        end  
        if rowHash["impto30"]==nil
          rowHash["impto30"]="0"
        end  
        if rowHash["mntneto"]==nil
          rowHash["mntneto"]="0"
        end 
        if rowHash["mntexe"]==nil
          rowHash["mntexe"]="0"
        end 
        if rowHash["mntiva"]==nil
          rowHash["mntiva"]="0"
        end 
        if rowHash["otrosimpto"]==nil
          rowHash["otrosimpto"]="0"
        end 

        doc = Docmanual.new(rowHash)
        if doc.tipodoc == 1
          doc.tipodoc = 30
        end
        if doc.tipodoc == 7
          doc.tipodoc = 35
        end  
        doc.save

        impto10 = rowHash["impto10"].to_f
        impto18 = rowHash["impto18"].to_f
        impto25 = rowHash["impto25"].to_f
        impto30 = rowHash["impto30"].to_f
        if impto10>0
          imptoH = Hash.new 
          imptoH["TipoImp"] = 10   
          imptoH["TasaImp"] = 10 
          imptoH["MontoImp"] = impto10 
          imptoH["docmanual_id"] = doc.id
          Otrosimpmanual.create! imptoH
        end  
        if impto18>0
          imptoH = Hash.new 
          imptoH["TipoImp"] = 18   
          imptoH["TasaImp"] = 18 
          imptoH["MontoImp"] =impto18 
          imptoH["docmanual_id"] =doc.id
          Otrosimpmanual.create! imptoH
        end  
        if impto25>0
          imptoH = Hash.new 
          imptoH["TipoImp"] = 25   
          imptoH["TasaImp"] = 25 
          imptoH["MontoImp"] = impto25 
          imptoH["docmanual_id"] = doc.id
          Otrosimpmanual.create! imptoH
        end  
        if impto30>0
          imptoH = Hash.new 
          imptoH["TipoImp"] = 30   
          imptoH["TasaImp"] = 30 
          imptoH["MontoImp"] = impto30 
          imptoH["docmanual_id"] = doc.id
          Otrosimpmanual.create! imptoH
        end  
        doc.otrosimpto = impto10 + impto18 + impto25 + impto30
        doc.save
      end  
    end
    return msg
  end
end

app/controllers/docmanuals_controller.rb
class DocmanualsController < ApplicationController
  before_action :set_docmanual, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @docmanuals = Docmanual.where(estado: "PREVIO").where(:rutemisor => Usuarioempresa.where(useremail:current_user.email).map {|u| u.rutempresa})
    totFmanual = Docmanual.select('sum("mntneto") as mntneto,sum("mntexe") as mntexe, sum("mntiva") as iva, sum("mnttotal") as mnttotal,sum(impto10+impto18+impto25+impto30) as otrosimp, count(*) as count').where('"estado" = ? AND "tipodoc" <> 52 and "tipodoc"<>60', "PREVIO").where(:rutemisor => Usuarioempresa.where(useremail:current_user.email).map {|u| u.rutempresa})
    totFmanual.map { |e| @totFmanual = e }
    
    respond_with(@docmanuals)
  end

  def destroy
    @docmanual.destroy
    respond_with(@docmanual)
  end

  def import
    @docmanuals = Docmanual.where(estado: "PREVIO").where(:rutemisor => Usuarioempresa.where(useremail:current_user.email).map {|u| u.rutempresa})
    totFmanual = Docmanual.select('sum("mntneto") as mntneto,sum("mntexe") as mntexe, sum("mntiva") as iva, sum("mnttotal") as mnttotal,sum(impto10+impto18+impto25+impto30) as otrosimp, count(*) as count').where('"tipodoc" <> 52 and "tipodoc"<>60').where(:rutemisor => Usuarioempresa.where(useremail:current_user.email).map {|u| u.rutempresa})
    totFmanual.map { |e| @totFmanual = e }
   
    @msg = Docmanual.import(params[:file])
    respond_to do |format|
      format.html {
        if @msg == " "
          render action: 'index', notice: "Documentos Ok"
        else
          render '/compmanuals/error'
        end  
      }
    end 
  end


  private
    def set_docmanual
      @docmanual = Docmanual.find(params[:id])
    end

    def docmanual_params
      params.require(:docmanual).permit(:tipodoc, :folio, :fchemis, :rutemisor, :rutrecep, :rznsocrecep, :mntneto, :mntexe, :mntiva, :otrosimpto, :mnttotal, :impto18, :impto10, :impto25, :impto30, :estado, :anulado)
    end
end

app/views/docmanuals/_form.html.haml
= simple_form_for(@docmanual) do |f|
  = f.error_notification

  .form-inputs
    = f.input :tipodoc
    = f.input :folio
    = f.input :fchemis
    = f.input :rutemisor
    = f.input :rutrecep
    = f.input :rznsocrecep
    = f.input :mntneto
    = f.input :mntexe
    = f.input :mntiva
    = f.input :otrosimpto
    = f.input :mnttotal
    = f.input :impto18
    = f.input :impto10
    = f.input :impto25
    = f.input :impto30
    = f.input :estado

  .form-actions
    = f.button :submit

app/views/docmanuals/edit.html.haml
%h1 Editing docmanual

= render 'form'

= link_to 'Show', @docmanual
\|
= link_to 'Back', docmanuals_path

app/views/docmanuals/index.html.haml
%h3 Documentos Manuales

%table.table.table-striped
  %thead
    %tr
      %th Tipodoc
      %th Folio
      %th Fchemis
      %th Rutemisor
      %th Rutrecep
      %th Rznsocrecep
      %th{:style => 'text-align: right;'} Mntneto
      %th{:style => 'text-align: right;'} Mntexe
      %th{:style => 'text-align: right;'} Mntiva
      %th{:style => 'text-align: right;'} Otrosimpto
      %th{:style => 'text-align: right;'} Mnttotal
      %th Estado
      %th
      
  %tbody
    - @docmanuals.each do |docmanual|
      %tr
        %td= docmanual.nombre_doc
        %td= docmanual.folio
        %td= docmanual.fchemis
        %td= docmanual.rutemisor
        %td= docmanual.rutrecep
        %td= docmanual.rznsocrecep
        %td{:style => 'text-align: right;'}= number_to_currency(docmanual.mntneto, precision: 0, delimiter: "." )+"&nbsp;".html_safe
        %td{:style => 'text-align: right;'}= number_to_currency(docmanual.mntexe, precision: 0, delimiter: "." )+"&nbsp;".html_safe
        %td{:style => 'text-align: right;'}= number_to_currency(docmanual.mntiva, precision: 0, delimiter: "." )+"&nbsp;".html_safe
        %td{:style => 'text-align: right;'}= number_to_currency(docmanual.otrosimpto, precision: 0, delimiter: "." )+"&nbsp;".html_safe
        %td{:style => 'text-align: right;'}= number_to_currency(docmanual.mnttotal, precision: 0, delimiter: "." )+"&nbsp;".html_safe
        %td= docmanual.estado
        %td= link_to 'Eliminar', docmanual, :method => :delete, :data => { :confirm => 'Seguro que desea eliminar?' }, class: "btn btn-primary btn-xs" 
  %tr
    %th
    %th
    %th
    %th
    %th
    %th{:style => 'text-align: right;'}= 'TOTALES'
    / %td{:style => 'text-align: right;'}= @totFmanual.count
    %td{:style => 'text-align: right;'}= number_to_currency(@totFmanual.mntneto.to_i, precision: 0, delimiter: "." )+"&nbsp;".html_safe 
    %td{:style => 'text-align: right;'}= number_to_currency(@totFmanual.mntexe.to_i, precision: 0, delimiter: "." )+"&nbsp;".html_safe
    %td{:style => 'text-align: right;'}= number_to_currency(@totFmanual.iva.to_i, precision: 0, delimiter: "." )+"&nbsp;".html_safe
    %td{:style => 'text-align: right;'}= number_to_currency(@totFmanual.otrosimp.to_i, precision: 0, delimiter: "." )+"&nbsp;".html_safe
    %td{:style => 'text-align: right;'}= number_to_currency(@totFmanual.mnttotal.to_i, precision: 0, delimiter: "." )+"&nbsp;".html_safe 
%br

/  = link_to 'New Docmanual', new_docmanual_path
%h2 Importar Documentos
= form_tag import_docmanuals_path, multipart: true do 
  = file_field_tag :file 
  = submit_tag "Importar" 

app/views/docmanuals/new.html.haml
%h1 New docmanual

= render 'form'

= link_to 'Back', docmanuals_path

app/views/docmanuals/show.html.haml
%p#notice= notice

%p
  %b Tipodoc:
  = @docmanual.tipodoc
%p
  %b Folio:
  = @docmanual.folio
%p
  %b Fchemis:
  = @docmanual.fchemis
%p
  %b Rutemisor:
  = @docmanual.rutemisor
%p
  %b Rutrecep:
  = @docmanual.rutrecep
%p
  %b Rznsocrecep:
  = @docmanual.rznsocrecep
%p
  %b Mntneto:
  = @docmanual.mntneto
%p
  %b Mntexe:
  = @docmanual.mntexe
%p
  %b Mntiva:
  = @docmanual.mntiva
%p
  %b Otrosimpto:
  = @docmanual.otrosimpto
%p
  %b Mnttotal:
  = @docmanual.mnttotal
%p
  %b Impto18:
  = @docmanual.impto18
%p
  %b Impto10:
  = @docmanual.impto10
%p
  %b Impto25:
  = @docmanual.impto25
%p
  %b Impto30:
  = @docmanual.impto30
%p
  %b Estado:
  = @docmanual.estado

= link_to 'Edit', edit_docmanual_path(@docmanual)
\|
= link_to 'Back', docmanuals_path